// THEME TOKENS — the single source of truth for the app's visual style.
//
// Every color, radius, and font is defined here as a named CSS custom property,
// for both light and dark. Two consumers derive from this one file:
//   1. tailwind.config.ts  — maps Tailwind theme names to the CSS vars
//      (var(--color-primary), var(--radius), var(--font-sans), ...), so utility
//      classes resolve to the tokens instead of hardcoded values.
//   2. app/globals.css     — the actual var VALUES, generated by tokenCss() and
//      injected for :root (light), prefers-color-scheme: dark, and [data-theme]
//      overrides.
//
// Editing this file restyles the whole app. No component should hardcode a
// color, radius, or font (enforced by the no-hardcoded-tokens guard test).

export type TokenMap = Record<string, string>;

// The PRD's canonical token names. Light and dark use the SAME names — only the
// values differ — so a component's `text-text` / `bg-surface` classes work in
// both modes without per-mode styling.
export const CANONICAL_TOKEN_NAMES = [
  "--color-primary",
  "--color-accent",
  "--color-surface",
  "--color-text",
  "--color-muted",
  "--radius",
  "--font-sans",
  "--space-1",
  "--space-2",
  "--space-4",
] as const;

export const lightTokens: TokenMap = {
  "--color-primary": "#0A6E7C",
  "--color-accent": "#F4A340",
  "--color-surface": "#FFFFFF",
  "--color-text": "#16292B",
  "--color-muted": "#5B6E70",
  "--radius": "12px",
  "--font-sans": "Inter, ui-sans-serif, system-ui, sans-serif",
  "--space-1": "4px",
  "--space-2": "8px",
  "--space-4": "16px",
};

export const darkTokens: TokenMap = {
  "--color-primary": "#2BB5C7",
  "--color-accent": "#F4A340",
  "--color-surface": "#0F1A1B",
  "--color-text": "#E8F1F2",
  "--color-muted": "#9DB4B6",
  "--radius": "12px",
  "--font-sans": "Inter, ui-sans-serif, system-ui, sans-serif",
  "--space-1": "4px",
  "--space-2": "8px",
  "--space-4": "16px",
};

// Tailwind theme, mapped to the CSS var NAMES (not values). The values stay in
// the CSS custom properties so this file remains the single source of color.
export const tailwindTheme = {
  colors: {
    primary: "var(--color-primary)",
    accent: "var(--color-accent)",
    surface: "var(--color-surface)",
    text: "var(--color-text)",
    muted: "var(--color-muted)",
  },
  fontFamily: {
    sans: "var(--font-sans)",
  },
  borderRadius: {
    DEFAULT: "var(--radius)",
  },
  spacing: {
    1: "var(--space-1)",
    2: "var(--space-2)",
    4: "var(--space-4)",
  },
} as const;

// CSS custom-property declarations, generated from the token maps so the values
// flow from this one file. Order matters: :root (light) → system-dark media
// query → explicit [data-theme] overrides (which win on source order).
function ruleBlock(selector: string, tokens: TokenMap): string {
  const decls = Object.entries(tokens)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join("\n");
  return `${selector} {\n${decls}\n}`;
}

export function tokenCss(): string {
  return [
    ruleBlock(":root", lightTokens),
    `@media (prefers-color-scheme: dark) {`,
    `  ${ruleBlock(":root:not([data-theme])", darkTokens).replace(/\n/g, "\n  ")}`,
    `}`,
    ruleBlock('[data-theme="dark"]', darkTokens),
    ruleBlock('[data-theme="light"]', lightTokens),
  ].join("\n");
}